name: learn-github-actions
run-name: Hello ${{ github.actor }}
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello ${{ github.actor }}."
      - run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$GITHUB_REPOSITORY/issues \
          -d '{"title":"Found a bug","body":"I'\''m having a problem with this.","labels":["bug"]}'
